version: '3.7'

services:
  node-forwarder:
    container_name: node-forwarder
    image: node-forwarder.local
    environment:
      - ABLY_KEY=yourkey
      - NODE_HOST=localhost
      - NODE_USER=youruser
      - NODE_PASSWORD=yoursecret
    restart: unless-stopped
